---
language: ruby
rvm:
- 2.5.7
- 2.6.5
sudo: false
cache: bundler
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/0357efbc3cba43430d2b
    on_success: change
    on_failure: always
    on_start: never
